### ISSUE TITLE
i2c.h

### ISSUE THREAD

**Issue by hobus1domini** [Preston-Sundar/PCA9685-Multi-Channel-Servo-Controller-Driver-for-AVR-ATmega#1]
Hi, is it possible for you to provide the i2c.h you used? It's pretty hard hard to nearly impossible to reverse engineer this (at least if you are at my level of experience 😅). I would be very grateful because I need this for a university project!

Best regards,
Dominic

**Comment by hobus1domini** [comment]
Okay, I found it via your OLED-IIC project. You should link the I2C library here also :)

**Comment by prestonsn** [comment]
Hey Hobus, I'm glad you found the OLED library haha! Sorry for not having them in the same place. I'll add that link!
