### ISSUE TITLE
Initialization of PCA9685 okay, but the LEDs/Servos no response....

### ISSUE THREAD

**Issue by KingZuluKing** [Preston-Sundar/PCA9685-Multi-Channel-Servo-Controller-Driver-for-AVR-ATmega#2]
Hi Preston, I was trying to use your code here on the AVR I have, and it seems that it does not generate any pwm pulse on pins, but I am sure that the initialization part is correct, due to the fact that the i2C transaction codes generated on AVR are received and they are Acks.

Any ideas where would be potential failure prone code...
David

**Comment by abdelkhalek9080** [comment]
> Hi Preston, I was trying to use your code here on the AVR I have, and it seems that it does not generate any pwm pulse on pins, but I am sure that the initialization part is correct, due to the fact that the i2C transaction codes generated on AVR are received and they are Acks.
> 
> Any ideas where would be potential failure prone code... David
same problem

**Comment by prestonsn** [comment]
Hey Abdel, 
I'm not sure what could be causing that and I don't have access to the required hardware to recreate the issue at the moment. @KingZuluKing Might be the only one who knows what went wrong.

**Comment by KingZuluKing** [comment]
@abdelkhalek9080 This library from @Preston-Sundar is fully functional. I got it working eventually, if i remember correct there are two types of i2C routines aka initializations for AVRs which are written not exactly the same. If you are using the i2C library not from Davide Gironi, but the second one, then might be an issue. Either you use consistently in your firmware the library which is used here, or you have to manually go through the firmware and change it, and write the functions which are in your version.

Hope this helps
